# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12THk83flwbNmZvfKbzLetDy45U_J5nDK
"""

# Install SpaCy and its English language model if needed
!pip install spacy
!python -m spacy download en_core_web_sm

import spacy
# Load SpaCy's English model
nlp = spacy.load("en_core_web_sm")

# Input sentence
sentence = "Barack Obama served as the 44th President of the United States and won the Nobel Peace Prize in 2009."
# Process the sentence
doc = nlp(sentence)

# Print entity details
for ent in doc.ents:
    print(f"Entity: {ent.text}, Label: {ent.label_}, Start: {ent.start_char}, End: {ent.end_char}")

"""#1. How does NER differ from POS tagging in NLP?
Ans:

*   NER (Named Entity Recognition) identifies and classifies real-world entities in text, such as people, organizations, locations, and dates.
*   POS tagging (Part-of-Speech tagging) assigns grammatical labels (e.g., noun, verb, adjective) to each word in the text, without identifying entities.
*   NER: "Barack Obama" → PERSON
*   POS tagging: "Barack" → Proper Noun, "Obama" → Proper Noun

#Describe two applications that use NER in the real world:
Ans:


*   Financial News: Automatically identifying company names, financial events, stock ticker symbols, and monetary values for quick insights and trading decisions.
*   Search Engines: Enhancing search results by identifying entities within queries to provide relevant information cards, news articles, and better-organized search results.
"""